### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by TenzinCHW** [EVERTims/auralization_engine_evertims#5]
I am on Ubuntu 18.04.3, running gcc 7.5.0 and used JUCE 6.0.1.

I am up to compiling the project using `make` but there seems to have been an error during compilation.

The first error is
```
../../Source/AudioIOComponent.h:128:65: error: ‘nonexistent’ is not a member of ‘juce::File’
     FileChooser chooser ("Select a Wave file to play...", File::nonexistent, "*.wav");
```

and the second is
```
../../Source/AudioIOComponent.h:206:74: error: no matching function for call to ‘juce::ScopedPointer<juce::FileOutputStream>::ScopedPointer(std::unique_ptr<juce::FileOutputStream>)’
     ScopedPointer<FileOutputStream> fileStream (file.createOutputStream());
```

I've tried to use an older version of JUCE (5.4.4) to generate the build files but to no avail.

Would appreciate any help.

**Comment by TenzinCHW** [comment]
I realised it was built with JUCE 5.3.2 so I tried that too but it doesn't work. After checking the git history of the file causing the error, I found that those lines have been there since the creation of the file `AudioIOComponent.h`.

Think it might be an Ubuntu problem. Will try with an older version of Ubuntu.

**Comment by TenzinCHW** [comment]
Okay got it working with JUCE 6.0.1.

`nonexistent` is deprecated so should just change it to `File()`.

`ScopedPointer` is also deprecated so should change it to `unique_ptr`.

There's also the change in Utils.h from the other issue which fixes finding `omni.sofa` and `directional.sofa`.

I also found that libmysofa offered a `mysofa_open_no_norm` function which I just plopped into `DirectivityHandler.h` since that was causing some problems too.

Hopefully I'll find some time to make a pull request.

**Comment by yipinghan** [comment]
Can you make a demo successfully by using this projects?

**Comment by TenzinCHW** [comment]
Hi yes. I have created a gist to install everything [here](https://gist.github.com/TenzinCHW/7427466f0a332940bac40e489ef4204f). You may need to change the path name for `data_dir` for all three files because I created these scripts for a live USB usage (have to install every time it reboots).

Unzip and then run `bash initial_setup.sh` and then `install_linux.sh`. You also will have to set up Juce files when Projucer pops up by clicking File > Open and then choosing the `EvertSE.jucer` from the Evertims/auralization_engine_evertims in the `data_dir` that you specified and finally saving project with Ctrl+P.

You'll be able to find the auralization engine in the folder `$data_dir/Evertims/aureng/build` and Evertims in `$data_dir/Evertims/evertims`.

To start it in Blender, you'll need to get the Blender addon and import it into Blender 2.79 and specify the auralization engine binary path (see above) and evertims binary and mat file (in the evertims folder).

I have made some fixes for Blender 2.80+ but the sample scene is wonky.

**Comment by ramagottfried** [comment]
same `File::nonexistent` errors here, with Projucer v7.0.5 on mac os

**Comment by TenzinCHW** [comment]
Sorry I've stopped any work on this as it was just for a friend's master's project which has since been completed. Though this is quite interesting and I might pick the auralization engine project up some time in the future.
